services:
  - type: web
    name: ielts-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install && npm rebuild sqlite3 --build-from-source
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
